version: "3.7"
services:
  frontend:
    build:
      context: ./frontend/.build/
      dockerfile: ./Dockerfile
    container_name: frontend
    hostname: frontend
    volumes:
      - ./frontend:/var/frontend
    ports:
      - "80:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frondend-npm_install-webpack:
    build:
      context: ./frondend-npm_install-webpack/.build/
      dockerfile: ./Dockerfile
    container_name: frondend-npm_install-webpack
    hostname: frondend-npm_install-webpack
    volumes:
      - ./frontend:/var/frondend-npm_install-webpack
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"